using System.Globalization;
using System.Text;
using System.Text.Json;

namespace Jef4Net.CodeGen;

internal static class HitachiMappingGenerator
{
    internal static string Generate(string dataDirectory)
    {
        var output = new StringBuilder("// <auto-generated />\nnamespace Jef4Net.Hitachi.Internal;\n\ninternal static class HitachiTables\n{\n");
        foreach (var definition in new[]
        {
            (File: "hitachi_ebcdic_mapping.json", Name: "Ebcdic", Size: 256),
            (File: "hitachi_ebcdik_mapping.json", Name: "Ebcdik", Size: 256),
            (File: "hitachi_keis78_mapping.json", Name: "Keis78", Size: 65536),
            (File: "hitachi_keis83_mapping.json", Name: "Keis83", Size: 65536),
        })
        {
            using var document = JsonDocument.Parse(File.ReadAllText(Path.Combine(dataDirectory, definition.File)));
            var decode = new ulong[definition.Size];
            var encode = new SortedDictionary<ulong, int>();
            foreach (JsonElement record in document.RootElement.EnumerateArray())
            {
                int code = Parse(record.GetProperty("code"));
                int scalar = Parse(record.GetProperty("unicode"));
                if ((uint)code >= definition.Size || scalar > 0x10FFFF || scalar is >= 0xD800 and <= 0xDFFF)
                    throw new InvalidDataException($"Invalid mapping in {definition.File}.");
                string[] options = record.GetProperty("options").EnumerateArray().Select(x => x.GetString()!).ToArray();
                if (options.Except(new[] { "compatible", "decode_only", "combination" }).Any())
                    throw new InvalidDataException($"Unknown option in {definition.File}.");
                ulong key = (ulong)(scalar + 1) << 21;
                // The SBCS sources intentionally repeat compatibility bytes (notably 8F/A8);
                // their normal entry follows the compatibility alias and therefore wins.
                if (decode[code] != 0 && decode[code] != key && definition.Size != 256)
                    throw new InvalidDataException($"Conflicting decode {code:X4}.");
                decode[code] = key;
                if (!options.Contains("decode_only")) encode[key] = code; // upstream JSON order wins
            }

            Emit(definition.Name + "Decode", "ulong", decode.Select(x => x.ToString(CultureInfo.InvariantCulture) + "UL"));
            Emit(definition.Name + "Keys", "ulong", encode.Keys.Select(x => x.ToString(CultureInfo.InvariantCulture) + "UL"));
            Emit(definition.Name + "Codes", "ushort", encode.Values.Select(x => x.ToString(CultureInfo.InvariantCulture)));
        }

        output.Append("}\n");
        return output.ToString();

        static int Parse(JsonElement value) => int.Parse(value.GetString()!, NumberStyles.HexNumber, CultureInfo.InvariantCulture);
        void Emit(string name, string type, IEnumerable<string> entries)
        {
            output.Append($"    internal static System.ReadOnlySpan<{type}> {name} => new {type}[]\n    {{\n");
            int index = 0;
            foreach (string value in entries)
            {
                if (index % 16 == 0) output.Append("        ");
                output.Append(value).Append(',').Append(++index % 16 == 0 ? '\n' : ' ');
            }
            if (index % 16 != 0) { output.Length--; output.Append('\n'); }
            output.Append("    };\n");
        }
    }
}
