using System.Globalization;
using System.Text;

namespace Jef4Net.CodeGen;

internal static class IbmMappingGenerator
{
    internal static string Generate(string dataDirectory)
    {
        UcmFile c1390 = UcmParser.Parse(Path.Combine(dataDirectory, "ibm-1390_P110-2003.ucm"));
        UcmFile c1399 = UcmParser.Parse(Path.Combine(dataDirectory, "ibm-1399_P110-2003.ucm"));
        Validate(c1390); Validate(c1399);
        Tables t1390 = Build(c1390); Tables t1399 = Build(c1399);
        if (!t1390.DbcsDecode.SequenceEqual(t1399.DbcsDecode) || !t1390.DbcsEncode.SequenceEqual(t1399.DbcsEncode))
            throw new InvalidDataException("The 1390 and 1399 DBCS 16684 mappings differ.");

        var output = new StringBuilder("// <auto-generated />\nnamespace Jef4Net.Ibm.Internal;\n\ninternal static class IbmTables\n{\n");
        Emit("Sbcs8482Decode", "ulong", t1390.SbcsDecode.Select(Number));
        EmitPairs("Sbcs8482", t1390.SbcsEncode);
        Emit("Sbcs5123Decode", "ulong", t1399.SbcsDecode.Select(Number));
        EmitPairs("Sbcs5123", t1399.SbcsEncode);
        Emit("Dbcs16684Decode", "ulong", t1390.DbcsDecode.Select(Number));
        EmitPairs("Dbcs16684", t1390.DbcsEncode);
        Emit("Dbcs16684Prefixes", "int", t1390.DbcsEncode.Keys.Where(x => KeySuffix(x) != 0).Select(KeyScalar).Distinct().Order().Select(x => x.ToString(CultureInfo.InvariantCulture)));
        output.Append("}\n"); return output.ToString();

        static string Number(ulong x) => x.ToString(CultureInfo.InvariantCulture) + "UL";
        void EmitPairs(string name, SortedDictionary<ulong, int> values)
        { Emit(name + "Keys", "ulong", values.Keys.Select(Number)); Emit(name + "Codes", "ushort", values.Values.Select(x => x.ToString(CultureInfo.InvariantCulture))); }
        void Emit(string name, string type, IEnumerable<string> entries)
        {
            output.Append($"    internal static System.ReadOnlySpan<{type}> {name} => new {type}[]\n    {{\n"); int i = 0;
            foreach (string value in entries) { if (i % 16 == 0) output.Append("        "); output.Append(value).Append(',').Append(++i % 16 == 0 ? '\n' : ' '); }
            if (i % 16 != 0) { output.Length--; output.Append('\n'); } output.Append("    };\n");
        }
    }

    private static void Validate(UcmFile file)
    {
        if (file.Headers.GetValueOrDefault("mb_cur_min") != "1" || file.Headers.GetValueOrDefault("mb_cur_max") != "2" || file.Headers.GetValueOrDefault("uconv_class") != "EBCDIC_STATEFUL") throw new InvalidDataException("Unexpected IBM UCM header.");
        if (file.States.Count != 6) throw new InvalidDataException("Unexpected IBM UCM state table.");
    }

    private static Tables Build(UcmFile file)
    {
        var sbcsDecode = new ulong[256]; var dbcsDecode = new ulong[65536];
        var sbcsEncode = new SortedDictionary<ulong, int>(); var dbcsEncode = new SortedDictionary<ulong, int>();
        foreach (UcmMapping m in file.Mappings)
        {
            ulong key = Key(m.Scalars); int code = m.Bytes.Aggregate(0, (v, b) => (v << 8) | b);
            ulong[] decode = m.Bytes.Length == 1 ? sbcsDecode : dbcsDecode; SortedDictionary<ulong, int> encode = m.Bytes.Length == 1 ? sbcsEncode : dbcsEncode;
            if (m.Direction is MappingDirection.RoundTrip or MappingDirection.DecodeOnly)
            { if (decode[code] != 0 && decode[code] != key) throw new InvalidDataException($"Conflicting IBM byte mapping {code:X4}."); decode[code] = key; }
            if (m.Direction is MappingDirection.RoundTrip or MappingDirection.EncodeOnly)
            { if (encode.TryGetValue(key, out int old) && old != code) throw new InvalidDataException($"Conflicting canonical Unicode mapping U+{KeyScalar(key):X}."); encode[key] = code; }
        }
        return new Tables(sbcsDecode, sbcsEncode, dbcsDecode, dbcsEncode);
    }
    private static ulong Key(int[] scalars) => ((ulong)(scalars[0] + 1) << 21) | (uint)(scalars.Length == 2 ? scalars[1] : 0);
    private static int KeyScalar(ulong key) => (int)(key >> 21) - 1;
    private static int KeySuffix(ulong key) => (int)(key & 0x1FFFFF);
    private sealed record Tables(ulong[] SbcsDecode, SortedDictionary<ulong, int> SbcsEncode, ulong[] DbcsDecode, SortedDictionary<ulong, int> DbcsEncode);
}
