using System.Globalization;
using System.Text;
using System.Text.Json;

namespace Jef4Net.CodeGen;

internal static class JbisMappingGenerator
{
    internal static string Generate(string directory)
    {
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(Path.Combine(directory, "JBIS_Unisys_MLS_reference.json")));
        JsonElement mappings = document.RootElement.GetProperty("sbcsMappings");
        var output = new StringBuilder("// <auto-generated />\nnamespace Jef4Net.Unisys.Jbis.Internal;\n\ninternal static class JbisTables\n{\n");
        EmitSbcs(output, mappings, "JisAscii", "jisAscii");
        EmitSbcs(output, mappings, "JapanEbcdic", "japanEbcdic");
        EmitSbcs(output, mappings, "JapanV24", "japanV24");
        output.Append("}\n"); return output.ToString();
    }

    private static void EmitSbcs(StringBuilder output, JsonElement root, string name, string property)
    {
        int[] values = Empty(256);
        foreach (JsonProperty item in root.GetProperty(property).EnumerateObject())
        {
            int code = int.Parse(item.Name, NumberStyles.HexNumber, CultureInfo.InvariantCulture);
            int scalar = int.Parse(item.Value.GetString()!, NumberStyles.HexNumber, CultureInfo.InvariantCulture);
            Add(values, code, scalar, property);
        }
        EmitPair(output, name, values);
    }

    private static void EmitPair(StringBuilder output, string name, int[] values)
    {
        Emit(output, $"{name}Decode", "int", values.Select(x => x.ToString(CultureInfo.InvariantCulture)));
        var encode = new SortedDictionary<int, int>();
        for (int code = 0; code < values.Length; code++)
            if (values[code] >= 0) encode.TryAdd(values[code], code);
        Emit(output, $"{name}EncodeKeys", "int", encode.Keys.Select(x => x.ToString(CultureInfo.InvariantCulture)));
        Emit(output, $"{name}EncodeCodes", "ushort", encode.Values.Select(x => x.ToString(CultureInfo.InvariantCulture)));
    }

    private static void Emit(StringBuilder output, string name, string type, IEnumerable<string> entries)
    {
        output.Append($"    internal static System.ReadOnlySpan<{type}> {name} => new {type}[]\n    {{\n");
        int index = 0;
        foreach (string entry in entries)
        {
            if (index % 16 == 0) output.Append("        ");
            output.Append(entry).Append(',');
            index++;
            output.Append(index % 16 == 0 ? '\n' : ' ');
        }
        if (index % 16 != 0) { output.Length--; output.Append('\n'); }
        output.Append("    };\n");
    }

    private static int[] Empty(int length) { var result = new int[length]; Array.Fill(result, -1); return result; }
    private static void Add(int[] values, int code, int scalar, string source)
    {
        if ((uint)code >= values.Length || scalar is < 0 or > 0x10FFFF || scalar is >= 0xD800 and <= 0xDFFF)
            throw new InvalidDataException($"Invalid mapping {code:X4} -> U+{scalar:X4} in {source}.");
        if (values[code] >= 0 && values[code] != scalar)
            throw new InvalidDataException($"Duplicate code {code:X4} in {source}.");
        values[code] = scalar;
    }
}
