using System.Globalization;
using System.Text;
using System.Text.Json;

namespace Jef4Net.CodeGen;

internal static class MappingGenerator
{
    internal static string Generate(string dataDirectory)
    {
        var output = new StringBuilder("// <auto-generated />\nnamespace Jef4Net.Fujitsu.Internal;\n\ninternal static class FujitsuTables\n{\n");
        foreach (var (file, name, size) in new[] { ("jef", "Jef", 65536), ("ebcdic_lower", "Lower", 256), ("ebcdic_kana", "Kana", 256), ("ebcdic_ascii", "Ascii", 256) })
        {
            using var doc = JsonDocument.Parse(File.ReadAllText(Path.Combine(dataDirectory, $"fujitsu_{file}_mapping.json")));
            var decode = new ulong[size];
            var encode = new SortedDictionary<ulong, int>();
            var records = new HashSet<string>();
            var encodeOptions = new Dictionary<ulong, HashSet<string>>();
            foreach (var r in doc.RootElement.EnumerateArray())
            {
                int code = Hex(r.GetProperty("code"));
                if (code < 0 || code >= size) throw new InvalidDataException("Code out of range.");
                int scalar = Scalar(r.GetProperty("unicode"));
                int suffix = r.TryGetProperty("sp", out var sp) ? Scalar(sp) : 0;
                foreach (var field in new[] { "hd", "aj1" })
                    if (r.TryGetProperty(field, out var v)) Scalar(v);
                var options = r.GetProperty("options").EnumerateArray().Select(v => v.GetString()!).ToHashSet();
                string[] allowed = ["oneway", "decode_only", "encode_only", "unmappable", "cjk_ci", "substitution", "variant_only", "compatible"];
                if (options.Except(allowed).Any() || (options.Contains("decode_only") && options.Contains("encode_only")))
                    throw new InvalidDataException("Unknown or conflicting options.");
                string identity = $"{code}:{scalar}:{suffix}:{(r.TryGetProperty("hd", out var hd) ? hd.GetString() : "")}:{(r.TryGetProperty("aj1", out var aj) ? aj.GetString() : "")}";
                if (!records.Add(identity)) throw new InvalidDataException($"Duplicate record: {identity}");
                if (r.TryGetProperty("hd", out _) || r.TryGetProperty("aj1", out _) || options.Contains("unmappable")) continue;
                // Scalar+1 reserves zero for undefined entries, including U+0000.
                ulong key = ((ulong)(scalar + 1) << 21) | (uint)suffix;
                if (!options.Contains("encode_only"))
                {
                    if (decode[code] != 0 && decode[code] != key && !options.Contains("cjk_ci")) throw new InvalidDataException($"Conflicting decode: {code:X}");
                    decode[code] = key;
                }
                if (!options.Contains("decode_only"))
                {
                    if (encode.TryGetValue(key, out int previous) && previous != code &&
                        !options.Overlaps(new[] { "oneway", "substitution" }) && !encodeOptions[key].Overlaps(new[] { "oneway", "substitution" }))
                        throw new InvalidDataException($"Ambiguous encode: {scalar:X} ({previous:X}, {code:X})");
                    encode[key] = code;
                    encodeOptions[key] = options;
                }
            }
            if (size == 65536)
            {
                var entries = decode.Distinct().OrderBy(v => v).ToArray();
                if (entries.Length > ushort.MaxValue) throw new InvalidDataException("Too many mapping entries.");
                var ids = entries.Select((value, index) => (value, index)).ToDictionary(v => v.value, v => v.index);
                Emit(name + "Ids", "ushort", decode.Select(v => ids[v].ToString(CultureInfo.InvariantCulture)));
                Emit(name + "Entries", "ulong", entries.Select(v => v.ToString(CultureInfo.InvariantCulture) + "UL"));
            }
            else Emit(name + "Decode", "ulong", decode.Select(v => v.ToString(CultureInfo.InvariantCulture) + "UL"));
            Emit(name + "Keys", "ulong", encode.Keys.Select(v => v.ToString(CultureInfo.InvariantCulture) + "UL"));
            Emit(name + "Codes", "ushort", encode.Values.Select(v => v.ToString(CultureInfo.InvariantCulture)));
            Emit(name + "Prefixes", "int", encode.Keys.Where(v => (v & 0x1FFFFF) != 0).Select(v => (int)(v >> 21) - 1).Distinct().Select(v => v.ToString(CultureInfo.InvariantCulture)));
        }
        output.Append("}\n");
        return output.ToString();
        int Hex(JsonElement v) => int.Parse(v.GetString()!, NumberStyles.HexNumber, CultureInfo.InvariantCulture);
        int Scalar(JsonElement v)
        {
            int s = Hex(v);
            if (s < 0 || s > 0x10FFFF || s is >= 0xD800 and <= 0xDFFF) throw new InvalidDataException("Invalid Unicode scalar.");
            return s;
        }
        void Emit(string name, string type, IEnumerable<string> entries)
        {
            output.Append($"    internal static System.ReadOnlySpan<{type}> {name} => new {type}[]\n    {{\n");
            int i = 0;
            foreach (string value in entries)
            {
                if (i % 16 == 0) output.Append("        ");
                output.Append(value).Append(',');
                output.Append(++i % 16 == 0 ? '\n' : ' ');
            }
            if (i % 16 != 0) { output.Length--; output.Append('\n'); }
            output.Append("    };\n");
        }
    }
}
