using System.Globalization;
using System.Text;
using System.Text.Json;

namespace Jef4Net.CodeGen;

internal static class NecMappingGenerator
{
    internal static string Generate(string dataDirectory)
    {
        var output = new StringBuilder("// <auto-generated />\nnamespace Jef4Net.Nec.Internal;\n\ninternal static class NecTables\n{\n");
        GenerateUnicode("nec_jis8_mapping.json", "Jis8", 256);
        GenerateUnicode("nec_ebcdik_mapping.json", "Ebcdik", 256);
        GenerateJips();
        GenerateByteMap();
        output.Append("}\n");
        return output.ToString();

        void GenerateUnicode(string file, string name, int size)
        {
            using var document = JsonDocument.Parse(File.ReadAllText(Path.Combine(dataDirectory, file)));
            var decode = new ulong[size]; var encode = new SortedDictionary<ulong, int>();
            foreach (JsonElement record in document.RootElement.EnumerateArray()) Add(record, decode, encode, false, file);
            Emit(name + "Decode", "ulong", decode.Select(Value)); Emit(name + "Keys", "ulong", encode.Keys.Select(Value)); Emit(name + "Codes", "ushort", encode.Values.Select(Number));
        }

        void GenerateJips()
        {
            using var document = JsonDocument.Parse(File.ReadAllText(Path.Combine(dataDirectory, "nec_jips_mapping.json")));
            var normal = new ulong[65536]; var hd = new ulong[65536];
            var normalEncode = new SortedDictionary<ulong, int>(); var hdEncode = new SortedDictionary<ulong, int>();
            foreach (JsonElement record in document.RootElement.EnumerateArray())
            {
                if (!record.TryGetProperty("hd", out _) && !record.TryGetProperty("aj1", out _))
                    Add(record, normal, normalEncode, false, "nec_jips_mapping.json");
                if (!record.TryGetProperty("aj1", out _))
                    Add(record, hd, hdEncode, true, "nec_jips_mapping.json");
            }
            Emit("JipsDecode", "ulong", normal.Select(Value)); Emit("JipsHdDecode", "ulong", hd.Select(Value));
            Emit("JipsKeys", "ulong", normalEncode.Keys.Select(Value)); Emit("JipsCodes", "ushort", normalEncode.Values.Select(Number));
            Emit("JipsHdKeys", "ulong", hdEncode.Keys.Select(Value)); Emit("JipsHdCodes", "ushort", hdEncode.Values.Select(Number));
        }

        void Add(JsonElement record, ulong[] decode, SortedDictionary<ulong, int> encode, bool hd, string file)
        {
            int code = Parse(record.GetProperty("code")); int scalar = Parse(record.GetProperty("unicode"));
            string[] options = record.GetProperty("options").EnumerateArray().Select(x => x.GetString()!).ToArray();
            if (options.Except(new[] { "decode_only", "oneway", "halfwidth", "fullwidth" }).Any()) throw new InvalidDataException($"Unknown option in {file}.");
            int suffix = hd && record.TryGetProperty("hd", out JsonElement h) ? Parse(h) : 0;
            ulong key = Key(scalar, suffix); decode[code] = key;
            if (!options.Contains("decode_only")) encode[key] = code;
        }

        void GenerateByteMap()
        {
            using var document = JsonDocument.Parse(File.ReadAllText(Path.Combine(dataDirectory, "nec_jis8_ebcdik_mapping.json")));
            var j2e = Enumerable.Repeat(-1, 256).ToArray(); var e2j = Enumerable.Repeat(-1, 256).ToArray();
            foreach (JsonElement r in document.RootElement.EnumerateArray())
            {
                int j = Parse(r.GetProperty("jis8")); int e = Parse(r.GetProperty("ebcdik"));
                if (j2e[j] >= 0 || e2j[e] >= 0) throw new InvalidDataException("Conflicting NEC J/E byte mapping.");
                j2e[j] = e; e2j[e] = j;
            }
            Emit("Jis8ToEbcdik", "short", j2e.Select(Number)); Emit("EbcdikToJis8", "short", e2j.Select(Number));
        }

        static int Parse(JsonElement value) => int.Parse(value.GetString()!, NumberStyles.HexNumber, CultureInfo.InvariantCulture);
        static ulong Key(int scalar, int suffix = 0) => ((ulong)(scalar + 1) << 21) | (uint)suffix;
        static string Value(ulong x) => x.ToString(CultureInfo.InvariantCulture) + "UL";
        static string Number(int x) => x.ToString(CultureInfo.InvariantCulture);
        void Emit(string name, string type, IEnumerable<string> entries)
        {
            output.Append($"    internal static System.ReadOnlySpan<{type}> {name} => new {type}[]\n    {{\n"); int index = 0;
            foreach (string value in entries) { if (index % 16 == 0) output.Append("        "); output.Append(value).Append(',').Append(++index % 16 == 0 ? '\n' : ' '); }
            if (index % 16 != 0) { output.Length--; output.Append('\n'); } output.Append("    };\n");
        }
    }
}
