using System.Globalization;
using System.Text;

namespace Jef4Net.CodeGen;

internal static class UnisysMappingGenerator
{
    internal static string Generate(string directory)
    {
        var sbcs = new int[256];
        Array.Fill(sbcs, -1);
        for (int code = 0; code <= 0x7F; code++) sbcs[code] = code;
        foreach (var (code, scalar) in Read(Path.Combine(directory, "US-ASCII-QUOTES.TXT")))
        {
            if ((uint)code > 0x7F) throw new InvalidDataException("ASCII quote code is out of range.");
            sbcs[code] = scalar;
        }
        foreach (var (code, scalar) in Read(Path.Combine(directory, "JIS0201.TXT")))
            if (code is >= 0xA1 and <= 0xDF) sbcs[code] = scalar;

        var dbcs = new int[65536];
        Array.Fill(dbcs, -1);
        foreach (var (jis, scalar) in Read(Path.Combine(directory, "JIS0208.TXT")))
        {
            ValidateJis(jis, "JIS0208.TXT");
            int code = jis == 0x2121 ? 0x2020 : jis + 0x8080;
            Add(dbcs, code, scalar, "JIS0208.TXT");
        }
        foreach (var (jis, scalar) in Read(Path.Combine(directory, "JIS0212.TXT")))
        {
            ValidateJis(jis, "JIS0212.TXT");
            Add(dbcs, jis + 0x8000, scalar, "JIS0212.TXT");
        }

        var output = new StringBuilder("// <auto-generated />\nnamespace Jef4Net.Unisys.Internal;\n\ninternal static class UnisysTables\n{\n");
        EmitDecode("SbcsDecode", sbcs);
        EmitEncode("Sbcs", sbcs);
        EmitDecode("DbcsDecode", dbcs);
        EmitEncode("Dbcs", dbcs);
        output.Append("}\n");
        return output.ToString();

        static void ValidateJis(int code, string file)
        {
            int first = code >> 8, second = code & 255;
            if (first is < 0x21 or > 0x7E || second is < 0x21 or > 0x7E)
                throw new InvalidDataException($"Out-of-range JIS code {code:X4} in {file}.");
        }
        static void Add(int[] table, int code, int scalar, string file)
        {
            if (scalar is < 0 or > 0x10FFFF or >= 0xD800 and <= 0xDFFF)
                throw new InvalidDataException($"Invalid Unicode scalar in {file}.");
            if (table[code] >= 0 && table[code] != scalar)
                throw new InvalidDataException($"Duplicate LETS-J code {code:X4} in {file}.");
            table[code] = scalar;
        }
        void EmitDecode(string name, int[] values)
        {
            output.Append($"    internal static System.ReadOnlySpan<int> {name} => new int[]\n    {{\n");
            Emit(values.Select(x => x.ToString(CultureInfo.InvariantCulture)));
        }
        void EmitEncode(string prefix, int[] values)
        {
            var map = new SortedDictionary<int, int>();
            for (int code = 0; code < values.Length; code++)
                if (values[code] >= 0 && !map.TryAdd(values[code], code))
                    throw new InvalidDataException($"Duplicate Unicode encode candidate U+{values[code]:X4}.");
            output.Append($"    internal static System.ReadOnlySpan<int> {prefix}EncodeKeys => new int[]\n    {{\n"); Emit(map.Keys.Select(x => x.ToString(CultureInfo.InvariantCulture)));
            output.Append($"    internal static System.ReadOnlySpan<ushort> {prefix}EncodeCodes => new ushort[]\n    {{\n"); Emit(map.Values.Select(x => x.ToString(CultureInfo.InvariantCulture)));
        }
        void Emit(IEnumerable<string> entries)
        {
            int i = 0;
            foreach (string entry in entries) { if (i % 16 == 0) output.Append("        "); output.Append(entry).Append(',').Append(++i % 16 == 0 ? '\n' : ' '); }
            if (i % 16 != 0) { output.Length--; output.Append('\n'); }
            output.Append("    };\n");
        }
    }

    private static IEnumerable<(int Code, int Scalar)> Read(string path)
    {
        foreach (string raw in File.ReadLines(path))
        {
            string line = raw.Split('#')[0].Trim();
            if (line.Length == 0) continue;
            string[] fields = line.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries);
            if (fields.Length < 2) throw new InvalidDataException($"Malformed mapping in {path}.");
            yield return (Parse(fields[0]), Parse(fields[1]));
        }
        static int Parse(string value) => int.Parse(value.StartsWith("0x", StringComparison.OrdinalIgnoreCase) ? value.Substring(2) : value, NumberStyles.HexNumber, CultureInfo.InvariantCulture);
    }
}
