<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject><LibraryTargetFramework Condition="'$(LibraryTargetFramework)' == ''">net10.0</LibraryTargetFramework></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio"><PrivateAssets>all</PrivateAssets></PackageReference>
    <ProjectReference Include="../../src/Jef4Net/Jef4Net.csproj" SetTargetFramework="TargetFramework=$(LibraryTargetFramework)" />
    <ProjectReference Include="../../src/Jef4Net.CodeGen/Jef4Net.CodeGen.csproj" />
    <None Include="../../data/jef4j/*mapping.json" Link="data/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../data/jbis/*.json" Link="data/jbis/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../data/unisys/*.TXT" Link="data/unisys/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../data/icu/ibm/*.ucm" Link="data/icu/ibm/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
